spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/trip
    username: root
    password: qazwsx1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
  jwt:
    secret: d29uc2Vvbnp6YW5nCg==