spring:
  #  datasource:
  #    url: jdbc:h2:mem:test
  #    username: sa
  #    password:
  #    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3307/trip
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
  h2:
    console:
      enabled: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200
    redis:
      password: 1234
      timeout: 600ms
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 30000
  jwt:
    secret: d29uc2Vvbnp6YW5nCg==
cloud:
  aws:
    credentials:
      access-key: key
      secret-key: key
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: deploy

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
